### ISSUE TITLE
IndexError: list index out of range in getting project borehole data

### ISSUE THREAD

**Issue by danpejobo** [emerald-geomodelling/libnadagclient#8]
C:\OSGeo4W64>python --version
Python 3.9.5

pip freeze
```
...
numpy==1.22.1
libnadagclient==0.0.4
libsgfdata==0.0.14
pandas==1.3.5
...

```
Test with the ID from the readme-file:
```
d = libnadagclient.get_project_borehole_data("306dc437-08f8-40f2-a918-7f65c423611b")
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\libnadagclient\__init__.py", line 140, in get_project_borehole_data
    for url in _get_project_zip_files(get_project_info(project_id)):
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\libnadagclient\__init__.py", line 82, in get_project_info
    return _get_info(r.html.find("table")[0])
IndexError: list index out of range
```

Same error with a random ID:
```
d = libnadagclient.get_project_borehole_data("09c35654-87de-4f12-a986-6ffb8b4b4a23")
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\libnadagclient\__init__.py", line 140, in get_project_borehole_data
    for url in _get_project_zip_files(get_project_info(project_id)):
  File "C:\OSGEO4~1\apps\Python39\lib\site-packages\libnadagclient\__init__.py", line 82, in get_project_info
    return _get_info(r.html.find("table")[0])
IndexError: list index out of range
```

**Comment by redhog** [comment]
I can not reproduce this with the same versions. My best guess is that nadag had a temporary problem where it returned an error page, while not refusing connections.
We should add some code to detect error pages and raise a better exception in those cases.
